// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MainContent': string;
  'container': string;
  'exchangeRate': string;
  'imgVal': string;
  'root': string;
  'rotate3d': string;
}
export const cssExports: CssExports;
export default cssExports;
