// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Title': string;
  'content': string;
  'subTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
